-- MySQL Script generated by MySQL Workbench
-- Sun May  4 17:55:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdprestamos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdprestamos` ;

-- -----------------------------------------------------
-- Schema bdprestamos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdprestamos` DEFAULT CHARACTER SET utf8mb3 ;
USE `bdprestamos` ;

-- -----------------------------------------------------
-- Table `bdprestamos`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`cliente` (
                                                       `idcliente` INT NOT NULL AUTO_INCREMENT,
                                                       `nombre` VARCHAR(45) NOT NULL,
                                                       `apellido` VARCHAR(45) NOT NULL,
                                                       `cui` VARCHAR(45) NOT NULL,
                                                       `fechanacimiento` DATE NOT NULL,
                                                       `direccion` VARCHAR(100) NOT NULL,
                                                       `correo` VARCHAR(45) NOT NULL,
                                                       `telefono` VARCHAR(45) NOT NULL,
                                                       `eliminado` CHAR(1) NOT NULL DEFAULT '0',
                                                       PRIMARY KEY (`idcliente`),
                                                       UNIQUE INDEX `cui_UNIQUE` (`cui` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 8
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`estadoprestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`estadoprestamo` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`estadoprestamo` (
                                                              `idestadoprestamo` INT NOT NULL AUTO_INCREMENT,
                                                              `nombreestadoprestamo` VARCHAR(45) NOT NULL,
                                                              `eliminado` CHAR(1) NOT NULL DEFAULT '0',
                                                              PRIMARY KEY (`idestadoprestamo`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`estadosolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`estadosolicitud` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`estadosolicitud` (
                                                               `idestadosolicitud` INT NOT NULL AUTO_INCREMENT,
                                                               `nombreestado` VARCHAR(45) NOT NULL,
                                                               `eliminado` CHAR(1) NOT NULL DEFAULT '0',
                                                               PRIMARY KEY (`idestadosolicitud`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`prestamo` (
                                                        `idprestamo` INT NOT NULL AUTO_INCREMENT,
                                                        `idsolicitudprestamo` INT NOT NULL,
                                                        `fechaaprobacion` DATE NOT NULL,
                                                        `estadoprestamo_idestadoprestamo` INT NOT NULL,
                                                        `idusuario` INT NULL DEFAULT NULL,
                                                        PRIMARY KEY (`idprestamo`),
                                                        UNIQUE INDEX `idSolicitudPrestamo_UNIQUE` (`idsolicitudprestamo` ASC) VISIBLE,
                                                        INDEX `fk_prestamo_estadoPrestamo1_idx` (`estadoprestamo_idestadoprestamo` ASC) VISIBLE,
                                                        CONSTRAINT `fk_prestamo_estadoPrestamo1`
                                                            FOREIGN KEY (`estadoprestamo_idestadoprestamo`)
                                                                REFERENCES `bdprestamos`.`estadoprestamo` (`idestadoprestamo`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 10
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`pagoprestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`pagoprestamo` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`pagoprestamo` (
                                                            `idpagoprestamo` INT NOT NULL AUTO_INCREMENT,
                                                            `fechapagoprestamo` DATE NOT NULL,
                                                            `montopagado` DECIMAL(10,2) NOT NULL,
                                                            `idusuario` INT NOT NULL,
                                                            `prestamo_idprestamo` INT NOT NULL,
                                                            PRIMARY KEY (`idpagoprestamo`),
                                                            INDEX `fk_pagoPrestamo_prestamo1_idx` (`prestamo_idprestamo` ASC) VISIBLE,
                                                            CONSTRAINT `fk_pagoPrestamo_prestamo1`
                                                                FOREIGN KEY (`prestamo_idprestamo`)
                                                                    REFERENCES `bdprestamos`.`prestamo` (`idprestamo`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 12
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`usuario` (
                                                       `idusuario` INT NOT NULL AUTO_INCREMENT,
                                                       `usuario` VARCHAR(45) NOT NULL,
                                                       `nombre` VARCHAR(45) NOT NULL,
                                                       `apellido` VARCHAR(45) NOT NULL,
                                                       `correo` VARCHAR(45) NOT NULL,
                                                       `puesto` VARCHAR(45) NOT NULL,
                                                       `password` VARCHAR(45) NOT NULL,
                                                       `eliminado` CHAR(1) NOT NULL DEFAULT '0',
                                                       PRIMARY KEY (`idusuario`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdprestamos`.`solicitudprestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdprestamos`.`solicitudprestamo` ;

CREATE TABLE IF NOT EXISTS `bdprestamos`.`solicitudprestamo` (
                                                                 `idsolicitudprestamo` INT NOT NULL AUTO_INCREMENT,
                                                                 `montosolicitado` DECIMAL(10,2) NOT NULL,
                                                                 `plazo` INT NOT NULL,
                                                                 `fechasolicitud` DATE NOT NULL,
                                                                 `cliente_idcliente` INT NOT NULL,
                                                                 `usuario_idusuario` INT NOT NULL,
                                                                 `estadosolicitud_idestadosolicitud` INT NOT NULL,
                                                                 `tasainteres` INT NULL DEFAULT NULL,
                                                                 PRIMARY KEY (`idsolicitudprestamo`),
                                                                 INDEX `fk_solicitudPrestamo_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
                                                                 INDEX `fk_solicitudPrestamo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
                                                                 INDEX `fk_solicitudPrestamo_estadoSolicitud1_idx` (`estadosolicitud_idestadosolicitud` ASC) VISIBLE,
                                                                 CONSTRAINT `fk_solicitudPrestamo_cliente`
                                                                     FOREIGN KEY (`cliente_idcliente`)
                                                                         REFERENCES `bdprestamos`.`cliente` (`idcliente`),
                                                                 CONSTRAINT `fk_solicitudPrestamo_estadoSolicitud1`
                                                                     FOREIGN KEY (`estadosolicitud_idestadosolicitud`)
                                                                         REFERENCES `bdprestamos`.`estadosolicitud` (`idestadosolicitud`),
                                                                 CONSTRAINT `fk_solicitudPrestamo_usuario1`
                                                                     FOREIGN KEY (`usuario_idusuario`)
                                                                         REFERENCES `bdprestamos`.`usuario` (`idusuario`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 16
    DEFAULT CHARACTER SET = utf8mb3;



-- Inserción de datos
INSERT INTO estadosolicitud(nombreestado, eliminado)
VALUES ('Aprobado', '0'), ('Rechazado', '0'), ('En proceso', '0');

INSERT INTO estadoprestamo(nombreestadoprestamo, eliminado)
VALUES ('Activo', '0'), ('Pagado', '0'), ('En mora', '0'), ('Cancelado', '0');

INSERT INTO usuario(usuario, nombre, apellido, correo, puesto, password, eliminado)
VALUES ('jperez', 'Jose', 'Pérez', 'jperez@gmail.com', 'Cajero', '1234', '0');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;